"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {CalendarDays,CheckCircle2,MapPin,Minus,Plus,Send,ShieldCheck,Store} from 'lucide-react';

type FieldErrors=Partial<Record<'name'|'phone'|'areaId'|'scheduledAt'|'address'|'quantity',string>>;
type ApiError={code?:string;error?:string;message?:string;fields?:Record<string,string>};
type Area={id:string;name:string;slug:string;surcharge:number};
type Partner={id:string;businessName:string;slug:string|null;customPrice:number|null;rating:number;ratingCount:number;completedOrders:number;logo:string|null;areas:{id:string;name:string;slug:string}[]};
type Service={id:string;name:string;basePrice:number;minimumCharge:number;pricingType:string;unit:string};
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);

export function CheckoutForm({service,areas,partner,defaultAreaId}:{service:Service;areas:Area[];partner?:Partner|null;defaultAreaId?:string}){
  const r=useRouter();const [busy,setBusy]=useState(false),[err,setErr]=useState(''),[fieldErrors,setFieldErrors]=useState<FieldErrors>({}),[coords,setCoords]=useState<{lat:number;lng:number}|null>(null),[quantity,setQuantity]=useState(1),[areaId,setAreaId]=useState(defaultAreaId||'');
  const area=areas.find(x=>x.id===areaId),subtotal=Math.max(service.minimumCharge,service.basePrice*quantity),total=subtotal+(area?.surcharge||0);
  const maxQty=20;
  const invalid=(key:keyof FieldErrors)=>fieldErrors[key]?{'aria-invalid':true as const,'aria-describedby':`${key}-error`}:{};
  function locate(){if(!navigator.geolocation){setErr('Lokasi perangkat tidak didukung browser ini. Silakan isi alamat secara manual.');return}navigator.geolocation.getCurrentPosition(x=>{setCoords({lat:x.coords.latitude,lng:x.coords.longitude});setErr('')},()=>setErr('Lokasi perangkat tidak dapat diakses. Silakan isi alamat secara manual.'))}
  function validate(f:FormData){const errors:FieldErrors={};const name=String(f.get('name')||'').trim(),phone=String(f.get('phone')||'').replace(/[^0-9+]/g,''),address=String(f.get('address')||'').trim(),selectedArea=String(f.get('areaId')||''),scheduledAt=String(f.get('scheduledAt')||''),qty=Number(f.get('quantity')||1);if(name.length<2)errors.name='Nama minimal 2 karakter.';if(!/^\+?[0-9]{8,16}$/.test(phone))errors.phone='Masukkan nomor HP/WhatsApp yang valid (8–16 digit).';if(!selectedArea)errors.areaId='Pilih area layanan.';if(!scheduledAt||Number.isNaN(new Date(scheduledAt).getTime()))errors.scheduledAt='Pilih jadwal layanan yang valid.';if(address.length<8)errors.address='Alamat terlalu singkat. Masukkan alamat lengkap minimal 8 karakter.';else if(address.length>500)errors.address='Alamat maksimal 500 karakter.';if(!Number.isInteger(qty)||qty<1||qty>maxQty)errors.quantity=`Jumlah harus antara 1 sampai ${maxQty}.`;return errors}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,f=new FormData(form),localErrors=validate(f);setFieldErrors(localErrors);setErr('');const first=Object.keys(localErrors)[0];if(first){requestAnimationFrame(()=>form.querySelector<HTMLElement>(`[name="${first}"]`)?.focus());return}setBusy(true);try{const body={serviceId:service.id,partnerId:partner?.id,areaId:f.get('areaId'),name:f.get('name'),phone:f.get('phone'),address:f.get('address'),scheduledAt:f.get('scheduledAt'),quantity:Number(f.get('quantity')||1),note:f.get('note'),locationNote:f.get('locationNote'),paymentMethod:f.get('paymentMethod'),latitude:coords?.lat,longitude:coords?.lng};const res=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)}),j=(await res.json().catch(()=>({}))) as ApiError&{publicId?:string};if(!res.ok){if(j.fields){const next:FieldErrors={};for(const [key,value] of Object.entries(j.fields))if(['name','phone','areaId','scheduledAt','address','quantity'].includes(key))next[key as keyof FieldErrors]=value;setFieldErrors(next);const firstServer=Object.keys(next)[0];if(firstServer)requestAnimationFrame(()=>form.querySelector<HTMLElement>(`[name="${firstServer}"]`)?.focus())}setErr(j.message||'Pesanan belum berhasil dibuat. Periksa kembali data dan coba lagi.');return}if(!j.publicId){setErr('Pesanan berhasil diproses tetapi nomor pesanan tidak diterima. Silakan hubungi JasaBatam.');return}r.push(`/pesanan/${j.publicId}`)}catch{setErr('Koneksi bermasalah. Silakan coba lagi.')}finally{setBusy(false)}}
  return <form onSubmit={submit} className="checkout-market-grid" noValidate>
    <section className="checkout-detail-card"><div className="checkout-section-title"><span><CalendarDays/></span><div><h2>Detail Pesanan</h2><p>Lengkapi data pesanan Anda</p></div></div><div className="checkout-form-grid">
      <label>Nama lengkap<input required minLength={2} maxLength={100} name="name" autoComplete="name" placeholder="Masukkan nama lengkap" {...invalid('name')}/>{fieldErrors.name&&<small id="name-error" className="field-error">{fieldErrors.name}</small>}</label>
      <label>No. HP / WhatsApp<input required name="phone" inputMode="tel" autoComplete="tel" placeholder="Contoh: 0812 3456 7890" {...invalid('phone')}/>{fieldErrors.phone&&<small id="phone-error" className="field-error">{fieldErrors.phone}</small>}</label>
      <label>Area<select required name="areaId" value={areaId} onChange={e=>setAreaId(e.target.value)} {...invalid('areaId')}><option value="">Pilih area</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{fieldErrors.areaId&&<small id="areaId-error" className="field-error">{fieldErrors.areaId}</small>}</label>
      <label>Jadwal<input required type="datetime-local" name="scheduledAt" {...invalid('scheduledAt')}/>{fieldErrors.scheduledAt&&<small id="scheduledAt-error" className="field-error">{fieldErrors.scheduledAt}</small>}</label>
      <label className="full">Alamat lengkap<textarea required minLength={8} maxLength={500} name="address" rows={3} autoComplete="street-address" placeholder="Contoh: Perumahan Golden City Blok RA No. 3, Bengkong, Batam" {...invalid('address')}/>{fieldErrors.address&&<small id="address-error" className="field-error">{fieldErrors.address}</small>}<small className="checkout-hint">Masukkan alamat lengkap minimal 8 karakter.</small></label>
      <label className="full">Patokan / catatan lokasi (opsional)<input name="locationNote" maxLength={300} placeholder="Contoh: rumah nomor 3, dekat masjid, gerbang warna hijau"/></label>
      <label>Jumlah<div className="quantity-control"><button type="button" onClick={()=>setQuantity(x=>Math.max(1,x-1))} aria-label="Kurangi jumlah"><Minus/></button><input name="quantity" value={quantity} onChange={e=>setQuantity(Math.min(maxQty,Math.max(1,Number(e.target.value)||1)))} inputMode="numeric" {...invalid('quantity')}/><button type="button" onClick={()=>setQuantity(x=>Math.min(maxQty,x+1))} aria-label="Tambah jumlah"><Plus/></button><b>{service.unit}</b></div>{fieldErrors.quantity&&<small id="quantity-error" className="field-error">{fieldErrors.quantity}</small>}</label>
      <label>Metode pembayaran<select name="paymentMethod"><option value="CASH">Bayar setelah layanan / Cash</option><option value="TRANSFER">Transfer</option></select></label>
      <label className="full">Catatan untuk mitra (opsional)<textarea name="note" rows={2} maxLength={1000} placeholder="Contoh: jemput pukul 10 pagi, ada antar kembali"/></label>
    </div><button type="button" className="checkout-location-button" onClick={locate}>{coords?<><CheckCircle2/> Lokasi perangkat tersimpan</>:<><MapPin/> Gunakan Lokasi Saya</>}</button>{coords&&<small className="checkout-hint">Koordinat hanya digunakan untuk matching dan validasi lokasi; jarak tidak dibuat jika koordinat mitra tidak tersedia.</small>}{err&&<p role="alert" className="checkout-api-error">{err}</p>}</section>
    <aside className="checkout-summary-stack"><section className="checkout-summary-card"><h2>Ringkasan Pesanan</h2><div className="checkout-summary-service"><div className="checkout-summary-logo">{partner?.logo?<img src={partner.logo} alt={`Logo ${partner.businessName}`}/>:<Store/>}</div><div><b>{service.name}</b><span>{partner?.businessName||'Mitra akan dipilih oleh sistem'}</span></div></div><dl><div><dt>Harga per {service.unit}</dt><dd>{money(service.basePrice)}</dd></div><div><dt>Jumlah</dt><dd>{quantity} {service.unit}</dd></div><div><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div>{area&&area.surcharge>0&&<div><dt>Biaya area</dt><dd>{money(area.surcharge)}</dd></div>}<div className="checkout-total"><dt>Total</dt><dd>{money(total)}</dd></div></dl><p className="checkout-summary-note">Harga final dihitung ulang di server dari database saat order dibuat.</p></section>
      {partner&&<section className="checkout-summary-card"><h2>Mitra Pilihan</h2><div className="checkout-partner-summary"><div><Store/><span><b>{partner.businessName}</b><small>{partner.ratingCount>0?`★ ${partner.rating.toFixed(1)} · ${partner.ratingCount} ulasan`:'Belum ada ulasan'}</small></span></div>{area&&<p><MapPin/> {area.name}</p>}<p><ShieldCheck/> Status operasional akan diverifikasi ulang saat submit.</p></div></section>}
    </aside>
    <div className="checkout-submit-bar"><button disabled={busy} className="btn primary checkout-confirm"><Send/>{busy?'Memproses...':'Konfirmasi Order'}</button><span><ShieldCheck/> Data Anda hanya digunakan untuk keperluan pemesanan.</span></div>
  </form>;
}
