'use client';
import {useState} from 'react';
import {MapPin,Upload,CheckCircle2,BriefcaseBusiness,UserRound,MapPinned} from 'lucide-react';
type Opt={id:string;name:string};
export function PartnerRegistrationForm({categories,services,areas}:{categories:Opt[];services:(Opt&{categoryId:string})[];areas:Opt[]}){
 const [categoryId,setCategoryId]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const [geo,setGeo]=useState<{lat:string;lng:string}|null>(null);
 const locate=()=>{if(!navigator.geolocation){setMsg('Browser tidak mendukung lokasi. Pilih area layanan secara manual.');return}navigator.geolocation.getCurrentPosition(p=>{setGeo({lat:String(p.coords.latitude),lng:String(p.coords.longitude)});setMsg('Lokasi berhasil ditambahkan.')},()=>setMsg('Lokasi tidak diizinkan. Tidak masalah, pilih area layanan secara manual.'),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})};
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg('');const form=e.currentTarget;const fd=new FormData(form);if(geo){fd.set('latitude',geo.lat);fd.set('longitude',geo.lng)}try{const r=await fetch('/api/partners/apply',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Pendaftaran gagal');form.reset();setCategoryId('');setGeo(null);setMsg('Pendaftaran berhasil dikirim. Tim JasaBatam akan memeriksa data Anda.')}catch(x){setMsg(x instanceof Error?x.message:'Pendaftaran gagal')}finally{setBusy(false)}}
 return <form className="partner-apply-form" onSubmit={submit}>
  <section className="partner-form-section"><div className="partner-form-title"><UserRound/><div><h2>Data Pribadi</h2><p>Data utama untuk verifikasi dan komunikasi.</p></div></div><div className="partner-form-grid"><label>Nama lengkap<input name="name" required minLength={3} maxLength={120}/></label><label>No. WhatsApp<input name="phone" required inputMode="tel" placeholder="08xxxxxxxxxx"/></label><label>Email <small>(opsional)</small><input name="email" type="email"/></label><label>NIK<input name="nik" required inputMode="numeric" minLength={16} maxLength={16}/></label></div></section>
  <section className="partner-form-section"><div className="partner-form-title"><BriefcaseBusiness/><div><h2>Keahlian & Usaha</h2><p>Pilih jasa yang benar-benar dapat Anda kerjakan.</p></div></div><div className="partner-form-grid"><label>Nama usaha / nama mitra<input name="businessName" required minLength={2} maxLength={120}/></label><label>Kategori utama<select value={categoryId} onChange={e=>setCategoryId(e.target.value)} required><option value="">Pilih kategori</option>{categories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="partner-span-2">Layanan<select name="serviceIds" multiple required size={Math.min(6,Math.max(3,services.filter(x=>!categoryId||x.categoryId===categoryId).length))}>{services.filter(x=>!categoryId||x.categoryId===categoryId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><small>Gunakan Ctrl/⌘ untuk memilih lebih dari satu layanan.</small></label><label>Pengalaman (tahun)<input name="experienceYears" type="number" min="0" max="60" defaultValue="1"/></label><label className="partner-span-2">Tentang keahlian Anda<textarea name="description" required minLength={20} maxLength={1000} placeholder="Ceritakan pengalaman, jenis pekerjaan, dan keunggulan layanan Anda."/></label></div></section>
  <section className="partner-form-section"><div className="partner-form-title"><MapPinned/><div><h2>Area & Lokasi</h2><p>Digunakan untuk mencocokkan order terdekat.</p></div></div><div className="partner-form-grid"><label className="partner-span-2">Alamat lengkap<textarea name="address" required minLength={10} maxLength={500}/></label><fieldset className="partner-span-2 partner-checks"><legend>Area layanan</legend>{areas.map(a=><label key={a.id}><input type="checkbox" name="areaIds" value={a.id}/>{a.name}</label>)}</fieldset><div className="partner-span-2 partner-location-box"><MapPin/><div><b>{geo?'Lokasi tersimpan':'Tambahkan titik lokasi usaha'}</b><p>{geo?`${Number(geo.lat).toFixed(5)}, ${Number(geo.lng).toFixed(5)}`:'Opsional, tetapi membantu menampilkan mitra berdasarkan jarak.'}</p></div><button type="button" className="btn outline" onClick={locate}>Gunakan Lokasi Saya</button></div></div></section>
  <section className="partner-form-section"><div className="partner-form-title"><Upload/><div><h2>Dokumen Verifikasi</h2><p>Format JPG, PNG, WebP atau PDF. Maksimal 8 MB/file.</p></div></div><div className="partner-form-grid"><label>Foto KTP<input name="ktp" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></label><label>Foto profil / logo<input name="profile" type="file" accept="image/jpeg,image/png,image/webp"/></label><label className="partner-span-2">Portofolio pekerjaan<input name="portfolio" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label></div></section>
  <label className="partner-consent"><input name="consent" type="checkbox" value="yes" required/>Saya menyatakan data yang diberikan benar dan menyetujui proses verifikasi JasaBatam.</label>
  {msg&&<div className={`partner-form-message ${msg.startsWith('Pendaftaran berhasil')?'success':''}`}>{msg.startsWith('Pendaftaran berhasil')&&<CheckCircle2/>}{msg}</div>}
  <button className="partner-submit" disabled={busy}>{busy?'Mengirim pendaftaran...':'Daftar Jadi Mitra'}</button>
 </form>
}
