'use client';
import {useState} from 'react';
import {Bot,Send,ShieldCheck} from 'lucide-react';
type Result={ok:boolean;message?:string;requiresConfirmation?:boolean;confirmationToken?:string;intent?:string;action?:string;data?:unknown;code?:string};
type Entry={from:'partner'|'agent';text:string;confirmationToken?:string;confirmed?:boolean};
export function PartnerAgentClient(){
  const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[entries,setEntries]=useState<Entry[]>([{from:'agent',text:'Saya dapat membaca order dan analytics toko Anda, serta menyiapkan perubahan operasional yang selalu membutuhkan konfirmasi sebelum dieksekusi.'}]);
  async function call(body:Record<string,string>){setBusy(true);try{const r=await fetch('/api/mitra/agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json() as Result;return j}catch{return {ok:false,message:'Koneksi ke agent gagal.'} as Result}finally{setBusy(false)}}
  async function send(e:React.FormEvent){e.preventDefault();const text=message.trim();if(!text||busy)return;setMessage('');setEntries(x=>[...x,{from:'partner',text}]);const j=await call({message:text});setEntries(x=>[...x,{from:'agent',text:j.message||'Permintaan tidak dapat diproses.',confirmationToken:j.requiresConfirmation?j.confirmationToken:undefined}])}
  async function confirm(index:number,token:string){if(busy)return;const j=await call({confirmationToken:token});setEntries(x=>x.map((row,i)=>i===index?{...row,confirmed:true}:row).concat({from:'agent',text:j.message||'Aksi tidak dapat dieksekusi.'}))}
  return <div className="agent-shell"><div className="agent-note"><ShieldCheck/> Partner scope berasal dari sesi login. Agent tidak menerima partnerId dari browser dan mutation tidak dijalankan tanpa konfirmasi.</div><div className="agent-chat">{entries.map((e,i)=><div key={i} className={`agent-bubble ${e.from}`}><b>{e.from==='agent'?<><Bot/> Agent Mitra</>:'Anda'}</b><p>{e.text}</p>{e.confirmationToken&&!e.confirmed&&<div className="agent-confirm"><button className="btn outline" onClick={()=>setEntries(x=>x.map((row,idx)=>idx===i?{...row,confirmed:true}:row))}>Batal</button><button className="btn primary" disabled={busy} onClick={()=>confirm(i,e.confirmationToken!)}>Konfirmasi</button></div>}{e.confirmed&&e.confirmationToken&&<small>Permintaan konfirmasi sudah ditutup.</small>}</div>)}</div><form className="agent-composer" onSubmit={send}><textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={1200} placeholder='Contoh: "order baru saya ada berapa?" atau "ubah Laundry Kiloan menjadi 8000"'/><button className="btn primary" disabled={busy||!message.trim()}><Send/> {busy?'Memproses...':'Kirim'}</button></form></div>
}
