import crypto from 'node:crypto';
import type {Prisma} from '@prisma/client';

export const STOREFRONT_GALLERY_LIMIT=12;
export const DEFAULT_RANKING_SETTINGS={minimumCompletedOrders:5,minimumRatingCount:3};

export function partnerSlug(input:string){const s=input.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);return s||'mitra'}
export async function uniquePartnerSlug(tx:Prisma.TransactionClient|typeof import('./db').db,businessName:string,excludeId?:string){const base=partnerSlug(businessName);let candidate=base;for(let i=2;i<1000;i++){const exists=await tx.partner.findFirst({where:{slug:candidate,...(excludeId?{id:{not:excludeId}}:{})},select:{id:true}});if(!exists)return candidate;candidate=`${base.slice(0,Math.max(1,70-String(i).length-1))}-${i}`}throw new Error('PARTNER_SLUG_EXHAUSTED')}
export function normalizePhone(v:string){const d=v.replace(/\D/g,'');return d.startsWith('0')?`62${d.slice(1)}`:d}
export function tokenHash(token:string){return crypto.createHash('sha256').update(token).digest('hex')}
export function haversineKm(lat1:number,lng1:number,lat2:number,lng2:number){const R=6371,toRad=(n:number)=>n*Math.PI/180,dLat=toRad(lat2-lat1),dLng=toRad(lng2-lng1);const a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
export function isListingEligible(p:{status:string;online:boolean;dispatchEnabled:boolean;storefrontStatus:string;user:{active:boolean}}){return p.user.active&&p.online&&p.dispatchEnabled&&!['REJECTED','SUSPENDED'].includes(p.status)&&p.storefrontStatus!=='HIDDEN'}
export function rankingScore(input:{averageRating:number;ratingCount:number;completedOrders:number;completionRate:number;responseRate:number;averageResponseMinutes:number;cancellationRate:number},settings=DEFAULT_RANKING_SETTINGS){const eligible=input.completedOrders>=settings.minimumCompletedOrders&&input.ratingCount>=settings.minimumRatingCount;const rating=Math.max(0,Math.min(1,input.averageRating/5));const completion=Math.max(0,Math.min(1,input.completionRate));const response=Math.max(0,Math.min(1,input.responseRate));const speed=Math.max(0,Math.min(1,1-input.averageResponseMinutes/240));const reliability=Math.max(0,Math.min(1,1-input.cancellationRate));const volumeConfidence=1-Math.exp(-input.completedOrders/25);const score=(rating*.34+completion*.22+response*.14+speed*.10+reliability*.20)*(.65+.35*volumeConfidence);return {eligible,score:Number(score.toFixed(5)),components:{ratingScore:rating,completionScore:completion,responseScore:response,speedScore:speed,reliabilityScore:reliability,volumeConfidence}}}
export function rankComparator(a:{score:number;completedOrders:number;ratingCount:number;partnerId:string},b:{score:number;completedOrders:number;ratingCount:number;partnerId:string}){return b.score-a.score||b.completedOrders-a.completedOrders||b.ratingCount-a.ratingCount||a.partnerId.localeCompare(b.partnerId)}
export function badges(p:{status:string;createdAt:Date;ratingAvg:number;ratingCount:number;completedOrders:number;averageResponseMinutes?:number|null}){const out:string[]=[];if(p.status==='APPROVED')out.push('Terverifikasi');if(p.ratingCount>=20&&p.ratingAvg>=4.7)out.push('Top Rated');if((p.averageResponseMinutes??999)<=15&&p.completedOrders>=5)out.push('Fast Response');if(p.completedOrders>=50)out.push('Banyak Dipesan');if(Date.now()-p.createdAt.getTime()<90*86400000)out.push('Partner Baru');return out}
export function minuteLabel(v:number|null){if(v==null)return 'Tutup';const h=Math.floor(v/60).toString().padStart(2,'0'),m=(v%60).toString().padStart(2,'0');return `${h}:${m}`}
export function safeJsonRecord(v:unknown):Record<string,unknown>{return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>: {}}
