import crypto from 'node:crypto';import {S3Client,PutObjectCommand,DeleteObjectCommand} from '@aws-sdk/client-s3';
const MAX=8*1024*1024;const allowed=new Set(['image/jpeg','image/png','image/webp','application/pdf']);
export function storageConfig(){const endpoint=process.env.S3_ENDPOINT?.trim(),region=process.env.S3_REGION?.trim()||'auto',bucket=process.env.S3_BUCKET?.trim(),accessKeyId=process.env.S3_ACCESS_KEY_ID?.trim(),secretAccessKey=process.env.S3_SECRET_ACCESS_KEY?.trim(),publicBase=process.env.S3_PUBLIC_BASE_URL?.trim();return {endpoint,region,bucket,accessKeyId,secretAccessKey,publicBase,configured:Boolean(endpoint&&bucket&&accessKeyId&&secretAccessKey&&publicBase)}}
function validMagic(type:string,b:Buffer){if(type==='image/jpeg')return b[0]===0xff&&b[1]===0xd8&&b[2]===0xff;if(type==='image/png')return b.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));if(type==='image/webp')return b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP';if(type==='application/pdf')return b.subarray(0,5).toString()==='%PDF-';return false}
export async function uploadObject(file:File,prefix:string){const c=storageConfig();if(!c.configured)throw new Error('STORAGE_NOT_CONFIGURED');if(file.size<=0||file.size>MAX)throw new Error('FILE_SIZE_INVALID');if(!allowed.has(file.type))throw new Error('FILE_TYPE_INVALID');const b=Buffer.from(await file.arrayBuffer());if(!validMagic(file.type,b))throw new Error('FILE_CONTENT_INVALID');const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':file.type==='image/webp'?'webp':'pdf';const key=`${prefix.replace(/[^a-z0-9/_-]/gi,'')}/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${ext}`;const client=new S3Client({endpoint:c.endpoint,region:c.region,forcePathStyle:true,credentials:{accessKeyId:c.accessKeyId!,secretAccessKey:c.secretAccessKey!}});await client.send(new PutObjectCommand({Bucket:c.bucket!,Key:key,Body:b,ContentType:file.type,CacheControl:'public,max-age=31536000,immutable'}));return {key,url:`${c.publicBase!.replace(/\/$/,'')}/${key}`,mimeType:file.type,sizeBytes:file.size,originalName:file.name}}
export const uploadPolicy={maxBytes:MAX,allowed:[...allowed]};

export async function deleteObject(key:string){const c=storageConfig();if(!c.configured)throw new Error('STORAGE_NOT_CONFIGURED');const client=new S3Client({endpoint:c.endpoint,region:c.region,forcePathStyle:true,credentials:{accessKeyId:c.accessKeyId!,secretAccessKey:c.secretAccessKey!}});await client.send(new DeleteObjectCommand({Bucket:c.bucket!,Key:key}))}
export function imageDimensions(type:string,b:Buffer):{width:number;height:number}|null{try{if(type==='image/png'&&b.length>=24)return {width:b.readUInt32BE(16),height:b.readUInt32BE(20)};if(type==='image/jpeg'){let o=2;while(o+9<b.length){if(b[o]!==0xff){o++;continue}const marker=b[o+1],len=b.readUInt16BE(o+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return {height:b.readUInt16BE(o+5),width:b.readUInt16BE(o+7)};o+=2+len}}if(type==='image/webp'&&b.length>=30&&b.subarray(12,16).toString()==='VP8X')return {width:1+b.readUIntLE(24,3),height:1+b.readUIntLE(27,3)}}catch{}return null}
export async function validateStorefrontImage(file:File,kind:'LOGO'|'PROFILE'|'BANNER'|'GALLERY'){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('IMAGE_TYPE_INVALID');if(file.size<=0||file.size>(kind==='BANNER'?8:6)*1024*1024)throw new Error('IMAGE_SIZE_INVALID');const b=Buffer.from(await file.arrayBuffer());if(!validMagic(file.type,b))throw new Error('IMAGE_CONTENT_INVALID');const d=imageDimensions(file.type,b);if(d){if(d.width<320||d.height<320)throw new Error('IMAGE_DIMENSIONS_TOO_SMALL');if(kind==='BANNER'){const ratio=d.width/d.height;if(ratio<2||ratio>3.5)throw new Error('BANNER_RATIO_INVALID')}if((kind==='LOGO'||kind==='PROFILE')&&Math.abs(d.width/d.height-1)>.2)throw new Error('LOGO_RATIO_INVALID')}return d}
