import Link from 'next/link';import {notFound} from 'next/navigation';import {PanelShell} from '@/components/PanelShell';import {PageHeader,StatusBadge,EmptyState} from '@/components/AdminBits';import {requireAdmin} from '@/lib/auth';import {db} from '@/lib/db';import {rupiah} from '@/lib/money';
export const dynamic='force-dynamic';
export default async function Page({params}:{params:Promise<{id:string}>}){
await requireAdmin(['SUPER_ADMIN','OPERATIONS','CS']);
const {id}=await params;
const c=await db.customerProfile.findUnique({
  where:{id},
  include:{
    user:true,
    addresses:{include:{area:true}},
    orders:{include:{items:true,partner:true},orderBy:{createdAt:'desc'},take:50},
    reviews:{include:{order:true},orderBy:{createdAt:'desc'}}
  }
});if(!c)notFound();const spending=c.orders.filter(o=>o.status==='COMPLETED').reduce((n,o)=>n+o.total,0);const disputes=await db.dispute.findMany({where:{order:{customerId:c.id}},include:{order:true},orderBy:{createdAt:'desc'},take:20});return <PanelShell kind="admin"><PageHeader title={c.name} description="Detail customer dan histori transaksi."><Link className="btn outline small" href="/admin/customers">Kembali</Link></PageHeader><div className="admin-grid-2"><div className="stack"><section className="admin-card"><h2 className="section-title">Profile</h2><div className="info-grid"><div className="info-item"><small>Phone</small><strong>{c.user.phone||'-'}</strong></div><div className="info-item"><small>Email</small><strong>{c.user.email||'-'}</strong></div><div className="info-item"><small>Status</small><StatusBadge status={c.user.active?'ACTIVE':'INACTIVE'}/></div><div className="info-item"><small>Total spending</small><strong>{rupiah(spending)}</strong></div></div></section><section className="admin-card"><h2 className="section-title">Addresses</h2>{c.addresses.length?c.addresses.map(a=><div className="kpi-row" key={a.id}><span>{a.label||'Alamat'} — {a.line1}</span><span>{a.area.name}</span></div>):<EmptyState title="Belum ada alamat"/>}</section><section className="admin-card"><h2 className="section-title">Order History</h2>{c.orders.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Service</th><th>Mitra</th><th>Status</th><th>Total</th></tr></thead><tbody>{c.orders.map(o=><tr key={o.id}><td><Link className="row-link" href={`/admin/orders/${o.publicId}`}>{o.publicId}</Link></td><td>{o.items[0]?.name||'-'}</td><td>{o.partner?.businessName||'-'}</td><td><StatusBadge status={o.status}/></td><td>{rupiah(o.total)}</td></tr>)}</tbody></table></div>:<EmptyState title="Belum ada order"/>}</section></div><div className="stack"><section className="admin-card"><h2 className="section-title">Reviews</h2>{c.reviews.length?c.reviews.map(r=><div className="kpi-row" key={r.id}><span>{r.order.publicId}</span><b>{r.rating}/5</b></div>):<EmptyState title="Belum ada review"/>}</section><section className="admin-card"><h2 className="section-title">Disputes</h2>{disputes.length?disputes.map(d=><div className="kpi-row" key={d.id}><Link href={`/admin/orders/${d.order.publicId}`}>{d.order.publicId}</Link><StatusBadge status={d.status}/></div>):<EmptyState title="Tidak ada dispute"/>}</section></div></div></PanelShell>}
